service: apollo-lambda
useDotenv: true
provider:
  name: aws
  runtime: nodejs18.x
  httpApi:
    cors: true
  environment:
    MONGODB_URI: ${env:MONGODB_URI}
    PRIVATE_KEY: ${env:PRIVATE_KEY}
    NODE_ENV: ${env:NODE_ENV}
functions:
  graphql:
    handler: ./src/index.graphqlHandler
    events:
      - httpApi:
          path: /
          method: POST
      - httpApi:
          path: /
          method: GET
plugins:
  - serverless-plugin-typescript
